### ISSUE TITLE
Support For HighCharts 6.0+

### ISSUE THREAD

**Issue by aaronhuisinga** [blacklabel/custom_events#102]
Currently, it seems that HighCharts v6.0+ doesn't work with Custom Events. 
When updating from v5 to v6, we're seeing the error "Uncaught Error: Highcharts error #16 (https://www.highcharts.com/errors/16)". 

It appears that although HighCharts is loaded, Custom Events is trying to re-load it. I'd guess this is likely due to Custom Events trying to require HighCharts v5.

**Comment by pawelfus** [comment]
Hi @aaronhuisinga 

Thanks for reporting the issue. Could you recreate this issue in jsFiddle? Our official demo looks fine: https://jsfiddle.net/BlackLabel/Utx8g/

**Comment by aaronhuisinga** [comment]
Hey @pawelfus, sorry for taking so long to get back to you!
Our issue appears when using NPM + Webpack for compiling dependencies. In the package.json file, you're depending on "highcharts": "^5.0.9". If we change our package.json file to "highcharts": "^6.0.7" (the current version), we end up with two instances of Highcharts when using the Custom Events plugin.

We have node_modules/highcharts (v6.0.7) and node_modules/highcharts-custom-events/node_modules/highcharts (v5.0.9). Webpack then tries to load both the 5.0 version when using the Custom Events plugin, and the 6.0 version which we load globally to a vendor.js file, causing the duplicate HighCharts versions being loaded.

I believe you just need to update the Highcharts version in the package.json file to allow for 6.0+ as well as 5.0+.

**Comment by pawelfus** [comment]
Thank you for the details!

@sebastianbochan - do we need to install Highcharts? Maybe we should simply remove this dependancy and let users install Highcharts?

**Comment by aaronhuisinga** [comment]
@sebastianbochan any update on this? Just changing the dependency to >=5.0.9 should indeed fix this.

**Comment by sebastianbochan** [comment]
Hi @aaronhuisinga 
Sorry for my late reply, I will fix the dependency this day.
