### ISSUE TITLE
Double Click event issue

### ISSUE THREAD

**Issue by Track01** [blacklabel/custom_events#104]
Hi,
I created a new highchart of type xrange and tried to apply custom events on the series.  the click event works but the double click is not working.
Please find below the code that im trying to implement:

https://jsfiddle.net/OGGeek/saqmd33p/

Please if you can advise where is the issue.
Thank you

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

_Internal note:_ columns are working fine and the dblclick doesn't work for the xrange on point level too.

**Comment by isweidan** [comment]
Great Job. It is so helpful
We are facing the same issue. Hope we can have a fix as soon as possible
Thanks

**Comment by sebastianbochan** [comment]
I will debug it and try to update the core.
