### ISSUE TITLE
events from legend do not contain any useful reference

### ISSUE THREAD

**Issue by fifeclub** [blacklabel/custom_events#105]
registering handlers for click, dblclick, contextMenu on the legend works, but the event passed into the function and this have nothing which I can find the series that was clicked on the legend.

When setting legendItemClick without this plugin - it works fine - this inside the callback contains the series that was clicked.
However the event handler for this plugin is different.
The object passed to the function is an svg element.
The this refers to a MouseEvent.
I can get at the text from the series in the legend by this.srcElement.firstChild.data.
But that's not good enough.
Hasn't this been worked through before?
Thanks!

**Comment by sebastianbochan** [comment]
Thank you for contacting us. 

Could you prepare a simple demo (as jsfiddle.net) which will allow me to debug it ?

**Comment by fifeclub** [comment]
http://jsfiddle.net/fifeclub/b33gc8qc/2/

**Comment by sebastianbochan** [comment]
Thank you for the demo, I will debug it and get back to you as soon as possible.

**Comment by fifeclub** [comment]
Thanks for helping!
I noticed too that the events on points also do not contain any reference to the point.
ie the contextmenu.
The normal click contains this.point where it is a reference to the closest point.
I've been using the other custom events plugin on highcharts to do this, but it doesn't handle legend.
So your plugin and theirs play well together but it would be great if your right click on points would work too

**Comment by sebastianbochan** [comment]
1. When I run the demo: https://jsfiddle.net/BlackLabel/Utx8g/ with or without customEvents I see reference to point i.e in the console:

![zrzut ekranu 2018-01-19 o 13 03 28](https://user-images.githubusercontent.com/2115686/35150074-2db1e4be-fd19-11e7-9641-e8eee4212e9e.png)

2. I updated the code, let me know if now all works properly.

**Comment by fifeclub** [comment]
1 - you are right - this is actually the point itself rather than an event with a reference to the point - I understand.
2 - I see the code update to legend in 2.0.19 - what elements should I refer to to  get access to the legend item/series that I clicked on?

**Comment by sebastianbochan** [comment]
2. In "this" object, there is series reference
