### ISSUE TITLE
Safari 8 both "contextmenu" and "click" functions are called

### ISSUE THREAD

**Issue by zeman** [blacklabel/custom_events#11]
Safari 8 show different behaviour from Chrome when using both "contextmenu" and "click" on an object. With Chrome only the "contextmenu" function get's called whereas with Safari 8 both functions get called.

I'd like a click on an object to go to one url vs a right click to a different url. This functions correctly in Chrome but in Safari the "click" action gets called instead.

In the demo the feedback message flashes between both messages using Safari.

**Comment by sebastianbochan** [comment]
Could you replicate your example as live demo ?

**Comment by sebastianbochan** [comment]
Reopen, when problem still appear.
