### ISSUE TITLE
onClick does not work on Sunburst

### ISSUE THREAD

**Issue by Odinsama** [blacklabel/custom_events#110]
So in Treemap I could quite easily add onClick to my series options by writing:
`options.events = {
				click: this.setSelection,
			}`
and then adding those options with:
`chart.addSeries(options, false)`

But when I do the identical steps in my very similar Sunburst component clicking on things do absolutely nothing, I can't make it run a console log even.

I know this is related to customEvents because commenting out custom events fixes the issue (but causes others elsewhere). And the only big difference I can tell between my Sunburst and Treemap is the modules they use from HighCharts IE _Sunburst(HighCharts) and treemap(HighCharts) at the top

**Comment by KacperMadej** [comment]
Hi @Odinsama 

Thank you for reporting about the problem.
Please add a live demo in JSFiddle.

**Comment by Odinsama** [comment]
@KacperMadej How do I add CustomEvents to JSfiddle? 
<script src="http://blacklabel.github.io/custom_events/customEvents.js"></script>
Just gives out a 404 not found error, and nothing else I tried seems to work either :\

**Comment by pawelfus** [comment]
Hi @Odinsama - it should be: `https://blacklabel.github.io/custom_events/js/customEvents.js` (missing `js` part in your example). You can also use our official demo and change what is needed: https://jsfiddle.net/BlackLabel/Utx8g/

**Comment by Odinsama** [comment]
@KacperMadej @pawelfus Okay here you go: http://jsfiddle.net/w8kof8t1/2/
Without customEvents the "it works!" gets logged out, with customEvents, not so much. And Like I said before the same code works wonderfully in Treemap, so there is probably some conflict between you guys and the _Sunburst module, because everything LOOKS like it should work

**Comment by pawelfus** [comment]
@Odinsama thanks you for the example! You are right, something is buggy here.
