### ISSUE TITLE
Double click call click event twice

### ISSUE THREAD

**Issue by balkarov** [blacklabel/custom_events#111]
Hello. Thank you for your library.
My code:
```
events.dblclick = function (event) {
     console.log("db", event);
};
events.click = function (event) {
     console.log("click", event);
};
```

Logs:
![1](https://user-images.githubusercontent.com/6030335/36423229-1f243a1e-1650-11e8-89a6-af737e2fff1c.PNG)

How to stopPropagandition click when I click double?

I created with setTimeout and clearTimeout, but I think it is a hack
```
var clickTimeoutID = null;
events.dblclick = function (event) {
    clearTimeout(clickTimeoutID);
    console.log("db", event);
};
events.click = function (event) {
    clearTimeout(clickTimeoutID);
    clickTimeoutID = setTimeout(function () {
          console.log("click", event);
     }, 300);
};
```

**Comment by KacperMadej** [comment]
Hi @balkarov 

Thank you for reporting about the problem.

It's a good hack. Some devices / browser have troubles with click vs double click events, so you code might be the one that will be used for the official fix.

**Comment by antoine35** [comment]
Hello,
Have you found a solution to solve this problem. I also have this concern with chrome, the click is raised twice before the dblclick ...
Thank you for your comeback.

**Comment by sebastianbochan** [comment]
The problem with double click in browsers (which Kacper mentioned about) is still valid. As a result we need to use available workaround as solution.
