### ISSUE TITLE
express dependency

### ISSUE THREAD

**Issue by jdonenine** [blacklabel/custom_events#115]
Is there any actual usage of express within the the library?  We're looking to use your library but since you're including express as a dependency we would need to get legal approval for all of express.  I didn't see anywhere within the code that seemed to be using express so I'm wondering if that dependency could be removed entirely?

**Comment by sebastianbochan** [comment]
Hi @jdonenine 
You are absolutely right, I will commit it in next release. Meanwhile you can edit package.json on your own.

**Comment by jdonenine** [comment]
I just tried to push a branch on which I went ahead and made the changes myself but I'm getting a permission denied when trying to push my branch.  If you can give me permission to push to the repo then I can submit a pull request for you to review.

**Comment by jdonenine** [comment]
Ignore that last comment, I think the problem is my local git setup.  I'll get the pull request up here in a few.

**Comment by jdonenine** [comment]
OK, maybe it is the repo.  Do you have it set so that only collaborators can push?  I've tried HTTPS and SSH both with the same results.  Anyhow, let me know if it's a restriction on your repo or still something screwed up on my end.

**Comment by sebastianbochan** [comment]
I will release a minor version today, so please stay on track with the thread.

**Comment by sebastianbochan** [comment]
Hi @jdonenine 
I released 2.1.1, let me know if all worked properly. If not, please reopen the ticket and attach some details.

**Comment by jdonenine** [comment]
Perfect.  Thanks.
