### ISSUE TITLE
pos of clicked axis label is not available in event handler

### ISSUE THREAD

**Issue by robbertbrak** [blacklabel/custom_events#118]
When I add a click event handler to an axis label, the value of the label is available in the event handler (see https://jsfiddle.net/Utx8g/1172/ and click on an x axis label). However, I would also like to have the pos (= index) of the clicked label. Would that be possible?

Looking at the code, I can see that the pos is returned in the `value` attribute of the `eventObject`: https://github.com/blacklabel/custom_events/blob/418d7999f10f4f7ad1f28cad5177dcd219e5c512/js/customEvents.js#L387, but it is overwritten later: https://github.com/blacklabel/custom_events/blob/418d7999f10f4f7ad1f28cad5177dcd219e5c512/js/customEvents.js#L267).

I propose adding a `pos` attribute to the `eventObject`. Do you think that's a good idea?

**Comment by pawelfus** [comment]
Hi @robbertbrak - I guess this is connected to Highcharts issue https://github.com/highcharts/highcharts/issues/8127, right? That change in value is related to the #95 issue. 

What you can do, is to pass on position in `data-$` attribute with `useHTML` flag set to true and retrieve this in callback: http://jsfiddle.net/9L5f73r8/36/

**Comment by pawelfus** [comment]
That part is up to @sebastianbochan - if this can be simply added as `eventObject.pos` then why not ;)

**Comment by frankie567** [comment]
I'm facing the same issue. Having access to the `pos` property (just like in a custom `formatter` function) would make sense and ease the development of callbacks specific to a single label.

**Comment by sebastianbochan** [comment]
Will take care about that, tomorrow.

**Comment by sebastianbochan** [comment]
Hi @robbertbrak @frankie567,
I added the reference to `pos`, please test and let me know if its exactly what you expect.

**Comment by frankie567** [comment]
It does work indeed exactly as expected! It saves me a `data-` attribute parsing. Thank you @sebastianbochan 👌

**Comment by robbertbrak** [comment]
@sebastianbochan Perfect, thanks!

**Comment by sebastianbochan** [comment]
Thank you for your feedback!
