### ISSUE TITLE
Select and Unselect point events not fired for Treemap

### ISSUE THREAD

**Issue by samuellawrentz** [blacklabel/custom_events#123]
Hi,
The **select** and **unselect** events that are provided by Highcharts as default for the series type - **treemap** is not fired after including customEvents.js.
Event reference: https://api.highcharts.com/highcharts/series.treemap.point.events.select

After removing the customEvents.js, the events are triggered as expected. Please find the issue reproduced in this Codepen. 
https://codepen.io/samuellawrentz/pen/qyZGdM?editors=1010

Thanks.

**Comment by sebastianbochan** [comment]
Hi @samuellawrentz,
Thank you for reporting. I will verify and fix it as soon as possible.

**Comment by samuellawrentz** [comment]
Hi @sebastianbochan 
Eventually, I found out a hotfix for that issue. I just added the select and unselect events to the `options.point.events` object that is cleared during the `init` call. It seems to work fine after that.

```
      // Add support for legendItemClick in pie chart
      if (userOptionsPointEvents) {
        options.point.events = {
          legendItemClick: userOptionsPointEvents && userOptionsPointEvents.legendItemClick,
          select: userOptionsPointEvents && userOptionsPointEvents.select,
          unselect: userOptionsPointEvents && userOptionsPointEvents.unselect
        };
      }
```

Is this a feasible solution?

**Comment by samuellawrentz** [comment]
Hi @sebastianbochan 
Could you please include the "click" event as well? Seems that the click event is not triggered as well. This was the hotfix I could think of
`      // Add support for legendItemClick in pie chart
      if (userOptionsPointEvents) {
        options.point.events = {
          legendItemClick: userOptionsPointEvents && userOptionsPointEvents.legendItemClick,
          select: userOptionsPointEvents && userOptionsPointEvents.select,
          unselect: userOptionsPointEvents && userOptionsPointEvents.unselect,
          click: userOptionsPointEvents && userOptionsPointEvents.click
        };
      }`
Thanks
Samuel

**Comment by sebastianbochan** [comment]
Hi @samuellawrentz,
I will fix it next week, cause now we are focus on Highcharts v7 release.

**Comment by sebastianbochan** [comment]
@samuellawrentz 
FYI I updated custom events plugin and in the v2.2.2, fix is applied.
