### ISSUE TITLE
Treemap drilldown functionality is prevented.

### ISSUE THREAD

**Issue by PaulDalek** [blacklabel/custom_events#131]
#### Expected behaviour
Drilling mechanism should work in treemap chart (in case allowDrillToNode is set to true) while using custom events script and with click event added to point through series.point.events.

#### Actual behaviour
It seems that the drilling functionality is prevented.

#### Live demo
https://jsfiddle.net/1drsnq5t/

**Comment by sebastianbochan** [comment]
You can call the default `drillToNode` action in the `point.events.click`.

```
    plotOptions: {
      series: {
        point: {
          events: {
            click: function (event) {
              this.series.onClickDrillToNode(event);
            }
          }
        }
      }
    },
```

**Demo:**
- https://jsfiddle.net/BlackLabel/vehw3kxy/
