### ISSUE TITLE
"Cannot read property 'call' of undefined" error on touch devices when 'dblclick' event defined

### ISSUE THREAD

**Issue by Denyllon** [blacklabel/custom_events#132]
### Actual Behaviour ###
When 'dblclick' event defined within point configuration, and that point is clicked, the error is thrown in browser's console.
```js
Uncaught TypeError: Cannot read property 'call' of undefined
    at customEvents.js:324
```

### Live demo & steps to reproduce ###
Live example: https://codepen.io/anon/pen/qgKZNB

1. Open codepen and developer console
2. Toggle the device view in browser's console:
<img width="330" alt="screenshot 2019-02-12 at 12 13 23" src="https://user-images.githubusercontent.com/15111955/52632471-f5dd5600-2ec1-11e9-863f-49197758c001.png">
<img width="352" alt="screenshot 2019-02-12 at 12 12 54" src="https://user-images.githubusercontent.com/15111955/52632484-01c91800-2ec2-11e9-838b-026a2a704acc.png">

3. Refresh the site.
4. Click (once) on point to see the error.

**Comment by sebastianbochan** [comment]
Thank you for reporting, I'm debugging it and will fix as soon as possible.

**Comment by Denyllon** [comment]
I've just eddited the steps to reproduce, because the described issue is only possible to reproduce when the responsive mode is turned on from the beginning.

**Comment by sebastianbochan** [comment]
Thank you for deitals, please test and if problem will come again, reopen the ticket.
