### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by aaronbeall** [blacklabel/custom_events#136]
According to docs this plugin should be used in a module environment like this:
```
import Highcharts from "highcharts";
import HighchartsCustomEvents from "highcharts-custom-events";

HighchartsCustomEvents(Highcharts);
```

However `highcharts-custom-events` has no [type definitions](https://www.highcharts.com/docs/advanced-chart-features/typescript), which leads to an error in TypeScript on the above code.

**Comment by sebastianbochan** [comment]
Hi @aaronbeall,
Thank you for reporting about the problem. Will check it as soon as possible.

**Comment by sebastianbochan** [comment]
Hi @aaronbeall,
I updated the plugin by commit: https://github.com/blacklabel/custom_events/commit/249d009a185ef180dab06c40ed50b83747f3934f

Please verify and if something will be wrong, reopen the ticket with details.

**Comment by aaronbeall** [comment]
@sebastianbochan Thanks for the quick update! However it doesn't work... seems that the published module does not include the `.d.ts` file referenced by the `types` field:

![image](https://user-images.githubusercontent.com/2973900/58200081-ee3b0380-7c9f-11e9-83e4-766b09ad5a7c.png)

**Comment by sebastianbochan** [comment]
Hi @aaronbeall,
Thank you for the feedback, I updated the `package.json` and publish with 3.0.1 version. Please verify and let me know if all worked properly.

**Comment by aaronbeall** [comment]
@sebastianbochan It works, thanks!

**Comment by sebastianbochan** [comment]
Sounds great, thank you!
