### ISSUE TITLE
Issue with drilldown/select functionality when using subtitle event

### ISSUE THREAD

**Issue by kmilic** [blacklabel/custom_events#138]
Hi,

I've tried using custom_events to get a click event for highmaps subtitle (clicking on subtitle does drillup), but encountered a problem.
Here's my example JSFiddle: https://jsfiddle.net/xoynps38/
This is basic highmaps drilldown example updated to have select/unselect functionality and drillup on clicking the subtitle text.
Steps to reproduce:
1. Do drilldown
2. Drill back up by clicking the subtitle
3. Click Toggle selection mode button to enter selection mode
4. Try selecting some countries - in about 50% of times you will get Uncaught TypeError: Cannot read property 'call' of undefined in customEvents.js line 378. This will prevent select/unselect events from firing.

NOTE: The issue is reproducible even with just using basic drilldown capability (just drill down and up few times), but I didn't notice any bad side effects apart from error log (i.e. drilldown/drillup events will still keep firing as opposed to select/unselect events)

As a workaround I tried implementing a NOOP click event on the point (the same place where select/unselect are). That stops exception from happening, but also prevents select/unselect events completely.

Can you please help me find a potential solution to this issue or a viable workaround.

Thanks

**Comment by sebastianbochan** [comment]
Hi @kmilic,
Thank you for reporting about the problem. I was able to reproduce it in simplified demo:
- https://jsfiddle.net/BlackLabel/68pq0k3y/

Will fix as soon as possible.
