### ISSUE TITLE
Importing custom events module causes chart.getSelectedPoints() to always return an empty list for all charts. 

### ISSUE THREAD

**Issue by krishnaku** [blacklabel/custom_events#145]
Hi Piotr,

Here is small example based on your existing custom events demo.

https://jsfiddle.net/d60tbg8m/1/

I just added a getSelectedPoints call inside the existing
override of the series.point.event handler in the demo. I would expect to see selected points here, but it always gives me an empty list. The real point of failure is multiple point selection which is where I need to access getSelectedPoints, if all I needed was single point selecttion, then I already know this from the event. But if I do shift-click to do a multiple point select getSelectedPoints always return empty set when custom_events is installed, but not otherwise.

There is a related issue https://github.com/highcharts/highcharts/issues/9099 that I filed when I ran into a similar issue a couple of years back. but I dont think this issue is related. That was a one-off error where the currently selected staged point was not being returned, which was counter-intuitive, but could be fixed in the handler, by simply adding the current event point to points returned by getSelectedEvents. But if getSelectedPoints always returns an empty list, I cannot work around it this way. Issue 9099 is fixed in Highcharts 8, I believe, but I dont think that is relevant in this situation anyway (I am on Highcharts 7).

I believe this is a bug in custom_events. As this prevents multiple point selection from working all across my app, it would be helpful to have a fix for this. Let me know if I should file this as a bug on the custom_events repo..

Krishna 

>> from Piotr

Hi,

Yes, you are right - we tested it and it is a bug that occurs after adding the plugin.
Could you report it on our GitHub so that we have it in tickets? -
Then It will be forwarded to the developers responsible for this module.

Kind Regards

The overall context for this bug is here: https://www.highcharts.com/forum/viewtopic.php?f=9&t=44223&view=unread&sid=7ab4e8851ac8e230d095716e07ced131#p156838

**Comment by pawelfus** [comment]
Thank you for reporting the issue @krishnaku 

You are right, it seems to be a bug in this module, we will check it.

**Comment by sebastianbochan** [comment]
Simplified demo:
- https://jsfiddle.net/BlackLabel/ct60onwh/
