### ISSUE TITLE
Click on xAxis label issues error "Cannot read property 'options' of undefined"

### ISSUE THREAD

**Issue by martindia** [blacklabel/custom_events#146]
Since the newest version Click event on xAxis label doesn't work and issues warning on customEvents.js line 374:
`if (isPoint && event === 'click' && elemObj.series.options.allowPointSelect)` with 
Cannot read property 'options' of undefined
    at SVGTextElement.<anonymous> (customEvents.js:374)

If 'click" changed to 'dblclik' event works as expected.

**Comment by sebastianbochan** [comment]
Thank you for the feedback, I will take care as soon as possible.

**Comment by martindia** [comment]
Hey! Much thanks for fast action @sebastianbochan  :) click event work as before, problem is gone.

**Comment by sebastianbochan** [comment]
Thank you for the feedback!
