### ISSUE TITLE
IE11 Error

### ISSUE THREAD

**Issue by kellyctaylor** [blacklabel/custom_events#147]
Recent update has caused a syntax error in IE11.

![image](https://user-images.githubusercontent.com/41919678/86600413-05a18280-bf6e-11ea-8669-a9c1d1f8260c.png)

I'm pretty certain that this comes from the fact that IE11 doesn't support arrow functions. https://github.com/blacklabel/custom_events/blob/994a69f54e9543ec9e18543bec585cf51b415a2f/js/customEvents.js#L178

**Comment by pawelfus** [comment]
Thanks for reporting the issue @kellyctaylor 

FYI @sebastianbochan
