### ISSUE TITLE
high chart angular support

### ISSUE THREAD

**Issue by muralip** [blacklabel/custom_events#148]
IS this plugin will support fro angular6??

**Comment by sebastianbochan** [comment]
Do you use highcharts angular wrapper or native angular ?

**Comment by muralip** [comment]
its angular application with highchart-angular package.

**Comment by sebastianbochan** [comment]
In the official documentation there is example of loading custom events module.

https://www.npmjs.com/package/highcharts-angular#to-load-a-plugin
