### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined     at SVGPathElement.<anonymous> (customEvents.js:395)

### ISSUE THREAD

**Issue by richie50** [blacklabel/custom_events#150]
Hi @sebastianbochan i'm getting this error if a click event is expected but not defined when using your package with highcharts . I will submit a pull request. I believe is a simple check for undefined.

**Comment by richie50** [comment]
https://github.com/blacklabel/custom_events/pull/151

**Comment by lsmtom** [comment]
I have the same issue when using the library with `highcharts-react-official`. I do believe a simple check for undefined will solve the issue. BTW, I do a workaround and wait for the official release of the fix. 

```javascript
HighchartsCustomEvent(Highcharts);
// Bug Fix: Custom event call undefined events
const customEvent = Highcharts.Chart.prototype.customEvent;
const orgAdd = customEvent.add;
const noop = () => {};
customEvent.add = (SVGelem, events, elemObj, eventElement, isPoint) => {
  if (events) {
    for (const key in events) {
      if (events[key] === undefined) {
        events[key] = noop;
      }
    }
  }
  orgAdd.call(this, SVGelem, events, elemObj, eventElement, isPoint);
};
```

**Comment by pawelfus** [comment]
Hi @richie50, @lsmtom 

Thanks for reporting the issue, and I'm sorry for the late reply. But could you also provide live demo of the issue? We will check it. Thanks!

**Comment by lsmtom** [comment]
@pawelfus 

Please check this [demo](https://codesandbox.io/s/highcharts-react-simple-chart-forked-tplup)  to reproduce the issue. The issue will only happened after the chart is re-rendered. You can click the "Refresh" button to trigger a re-render and then click any bar in the chart.

You will get an "Cannot read property 'call' of undefined" error in Chrome, and an "events[event] is undefined" error in Firefox.

**Comment by pawelfus** [comment]
Thanks for the demo @lsmtom

**Comment by Christopher2K** [comment]
Hi. I don't believe a simple undefined check will solve the issue. I actually have this problem while a click listener is set.

**Comment by miron4dev** [comment]
I faced the same issue. Any news about it?

**Comment by sebastianbochan** [comment]
Hi @miron4dev,
Could you share a live demo of a problem? Do you have the same code as @lsmtom ?

**Comment by miron4dev** [comment]
Hi @sebastianbochan

Yes, my code is very similar to @lsmtom 

package.json:
```json
"highcharts": "^8.0.4",
"highcharts-custom-events": "^3.0.9",
"highcharts-react-official": "^3.0.0",
```

**Comment by julioxavierr** [comment]
+1

**Comment by ShimaMax** [comment]
+1

**Comment by sebastianbochan** [comment]
I will take care of it next week.

**Comment by taltultc** [comment]
+1

**Comment by erezstmn-doit** [comment]
+1

**Comment by sebastianbochan** [comment]
I'm working on it and will get back to you with feedback today.

**Comment by sebastianbochan** [comment]
I fixed the issue, please let me know if you have any problems.

**Comment by taltultc** [comment]
Thank you very much
