### ISSUE TITLE
Context menu with polygon series not working

### ISSUE THREAD

**Issue by govinda18** [blacklabel/custom_events#152]
Custom events (tested for contextmenu) does not work for polygon series.

Reproducer: http://jsfiddle.net/m42bxuaf/1/

**Comment by sebastianbochan** [comment]
Hi @govinda18,
Points in polygon declare an area, so the event should be defined for series not a particular point.

```
plotOptions: {
      series: {
          events: {
            click: function() {
              console.log('a');
            },
            contextmenu: () => console.log("Asd")
          }
      }
    },
```

Demo: http://jsfiddle.net/BlackLabel/3y1jetqk/

ps. I advise to use the newest Highcharts 8.2 instead of 5.x
