### ISSUE TITLE
3.0.10 not loading on CDN in jsdelivr.com

### ISSUE THREAD

**Issue by KacperMadej** [blacklabel/custom_events#156]
Looks like this is caused by the lack of tag in the repo - the last is 3.0.9 and that is loaded when using https://www.jsdelivr.com/

tags: https://github.com/blacklabel/custom_events/releases
CDN link: https://cdn.jsdelivr.net/gh//blacklabel/custom_events/js/customEvents.js

**Comment by pawelfus** [comment]
Thanks! Added 👍
