### ISSUE TITLE
Event to bar category

### ISSUE THREAD

**Issue by theking2** [blacklabel/custom_events#163]
Is there a way to attach an event to the category area (mouse over lightblue) and get the name of the category for further processing?
![image](https://user-images.githubusercontent.com/1612152/229043737-59ed98a5-9715-4765-8f78-0e1526980179.png)

**Comment by mfilipiec** [comment]
Yes, you can use the `mouseover` event on plotBands and refer to some information from the chart via `this`:

```JavaScript
xAxis: {
  plotBands: [{
    from: 1.5,
    to: 3.5,
    events: {
      mouseover: function () {
        console.log('mouseover on plotband', this);
      }
    }
  }]
}
```

Demo: https://jsfiddle.net/BlackLabel/d1oynfaq/
