### ISSUE TITLE
Point events missing in Highstock

### ISSUE THREAD

**Issue by sebastianbochan** [blacklabel/custom_events#35]
Issue with events per particular points.

**Comment by keithmdragon** [comment]
any eta on a fix or patch for this? its working fine on an older version of highstock (2.1.9), but this is preventing me from going to the latest version of highstock, which is needed to address some other issues i'm having

here is an example for the point event issue: http://jsfiddle.net/kdragon/Utx8g/570/
see the errors in the console when u left click on points

Uncaught TypeError: Cannot read property 'call' of null @ highstock.src.js:1319 
fireEvent @ highstock.src.js:1319
Pointer.onContainerClick @ highstock.src.js:10612
container.onclick @ highstock.src.js:10652

in my app (not the fiddle), i also see this stack trace, creating the chart, having trouble recreating this in a fiddle, but think it might be related to the other error. i can work more to recreate this in a fiddle if it is needed:

highstock.src.js:1166 Uncaught TypeError: Cannot read property 'hcEvents' of undefinedaddEvent @ highstock.src.js:1166
(anonymous function) @ customEvents.js:130customEvent.add @ customEvents.js:142
(anonymous function) @ customEvents.js:295
obj.(anonymous function) @ highstock.src.js:670
Series.render @ highstock.src.js:15223
(anonymous function) @ highstock.src.js:24333
obj.(anonymous function) @ highstock.src.js:670
(anonymous function) @ highstock.src.js:12944
each @ highstock.src.js:1158
Chart.renderSeries @ highstock.src.js:12942
Chart.render @ highstock.src.js:13050
Chart.firstRender @ highstock.src.js:13224
Chart.init @ highstock.src.js:11953
(anonymous function) @ highstock.src.js:22810
obj.(anonymous function) @ highstock.src.js:670
(anonymous function) @ highstock.src.js:23642
obj.(anonymous function) @ highstock.src.js:670
Chart.getArgs @ highstock.src.js:11858
Highcharts.Chart @ highstock.src.js:11832

Thanks
Keith
