### ISSUE TITLE
events at the series level of Flags don't work

### ISSUE THREAD

**Issue by keithmdragon** [blacklabel/custom_events#36]
neither the click nor contextMenu events work at the series level of flags. if u remove the customEvent.js script, click events will work. they work fine at the plotOptions level, but that means that they are applied to all series.

http://jsfiddle.net/kdragon/Ltjs0j5v/2/

**Comment by Newan** [comment]
with this code I get the click event but no event contextmenu: 


`
        data: [{
          x: Date.UTC(year, 1, 22),
          title: 'A',
          text: 'Shape: "squarepin"',
          events: {
          	click: function() {
            	alert("click");
          	},
          	contextmenu: function() {
            	alert("context");
          	}
        	},
        }],
`

**Comment by sebastianbochan** [comment]
Thank you for the reporting, I will check that.

**Comment by sebastianbochan** [comment]
You should declare events in the point object: 

```
point:{
   events: {
      click: function() {
            alert("click");
      },
      contextmenu: function() {
            alert("context");
      }
   }
},
```
