### ISSUE TITLE
It doesn't work with HighStock

### ISSUE THREAD

**Issue by blwoosky** [blacklabel/custom_events#40]
When i use this Plugin with highstock,
There is an error : Uncaught TypeError: Cannot read property 'plotLines' of undefined .

**Comment by sebastianbochan** [comment]
Do you use the newest custom-events? Could you setup demo ?

**Comment by theZiki** [comment]
I doesn't work with HighStock 4.2.1.

**Comment by cccCody** [comment]
I just created a pull request for what I did to get it working with highstock: https://github.com/blacklabel/custom_events/pull/44
