### ISSUE TITLE
Uncaught TypeError: Cannot set property 'isDirty' of undefined

### ISSUE THREAD

**Issue by nanatiris** [blacklabel/custom_events#43]
Getting error "Uncaught TypeError: Cannot set property 'isDirty' of undefined" when rendering a Pie chart.

Seems like the if statement was removed:
`if (chart.hasOwnProperty("xAxis") && chart.xAxis.length > 0) {
    chart.xAxis[0].isDirty = true;
 }`

Putting it back would fix the issue.
Thanks!

**Comment by sebastianbochan** [comment]
I was not able to replicate that issue

Demo: http://jsfiddle.net/2rg0ak7g/

Could you update my code with yours to introduce the problem?

**Comment by nanatiris** [comment]
I cannot reproduce the issue anymore using the latest version of customEvents (v1.4.0)

**Comment by sebastianbochan** [comment]
@nanatiris thank you for the feedback.
