### ISSUE TITLE
Custom events destroy hide events

### ISSUE THREAD

**Issue by eskimoblood** [blacklabel/custom_events#47]
I have a chart with a custom `hide` event. Adding the `custom_event.js` file this events will not work anymore.

The bug happens in line 19501 (`series[key][showOrHide]()`) of highcharts.js

```
      // show or hide elements
     each(['group', 'dataLabelsGroup', 'markerGroup', 'tracker'], function (key) {
       if (series[key]) {
         series[key][showOrHide]();
       }
     });
```

Fiddle: http://jsfiddle.net/gm7ecvh2/

So the problem is that `series[key]` should be a function but is `true`, which is set in the `custom_event.js` in [line 142](https://github.com/blacklabel/custom_events/blob/master/customEvents.js#L142).

**Comment by eskimoblood** [comment]
Wouldn't moving the line into the if block fix the problem?
```
var customEvent = HC.Chart.prototype.customEvent = function (obj, proto) {
  customEvent.add = function (elem, events, obj) {
    for (var key in events) {
      (function (key) {
        if (events.hasOwnProperty(key) && elem) {
          if ((!elem[key] || elem[key] === UNDEFINED) && elem.element) {
            HC.addEvent(elem.element, key, function (e) {
              if (obj.textStr) //labels
                obj.value = obj.textStr;
              events[key].call(obj, e);
              return false;
            });
            elem[key] = true;
          }
        }
      })(key);
    }
  };
```

**Comment by sebastianbochan** [comment]
Closed with commit: https://github.com/blacklabel/custom_events/commit/aacf9d41ea5a60c6191bfae61f9e40681bcc63b9
