### ISSUE TITLE
Clippaths wrong size - markers aren't visible

### ISSUE THREAD

**Issue by mikeapr4** [blacklabel/custom_events#50]
See here:
http://jsfiddle.net/yhLwgmh4/

Resizing the chart after load is part of the problem, also the point rendering outside the viewable area of the chart (parent container clipping) seems related too.

I have confirmed that without the custom events plugin included the markers are visible, also when the clippaths are explicitly set after the resize.

**Comment by sebastianbochan** [comment]
Thank you for the reporting, I will take a look for that as soon as possibe.

**Comment by sebastianbochan** [comment]
The issue is related with the Highcharts issue, reported here: https://github.com/highcharts/highcharts/issues/5442

**Comment by mikeapr4** [comment]
I'm not so sure, @sebastianbochan , if I take your http://jsfiddle.net/nrbfteby/ and comment out the custom events script tag, it works fine.

**Comment by sebastianbochan** [comment]
The reported bug is when we call series.update() with animation and then i.e chart.redraw(). The combination of that, we use in customEvents.

**Comment by mikeapr4** [comment]
I see the failure if your jsfiddle, but when I do not include the custom_events code it's not reproduceable (http://jsfiddle.net/5txzhzn5/), maybe there is still a defect, let's see what the Highcharts guys say.

**Comment by sebastianbochan** [comment]
@mikeapr4 I found a workaround, let me know if you find any issues.

**Comment by mikeapr4** [comment]
Just to confirm, v4.2.6 of HighCharts fixed the issue, as you said, the defect was in HighCharts. Thanks!
