### ISSUE TITLE
How I know which item I have clicked on legend

### ISSUE THREAD

**Issue by whrocha** [blacklabel/custom_events#52]
Hi guys, I have an doubt, how could I know which item I clicked on legend Item, e.g., I have 2 series on legend and I want to know if that item I clicked and know if that item are visible or unvisible,

**Comment by sebastianbochan** [comment]
The behaviour of legendItemClick is the same as default in Highcharts. In the "this" object, you have reference to the series and visible status.

Example:
- http://jsfiddle.net/hfvtrypq/
