### ISSUE TITLE
Wrong value in this object

### ISSUE THREAD

**Issue by sebastianbochan** [blacklabel/custom_events#54]
Series and point "this" object is wrong.

**Comment by kksevta** [comment]
This issue still exists
I am trying to get series name but its not working properly.
http://jsfiddle.net/mntd7wz9/

also point click is not working for me in firefox

**Comment by sebastianbochan** [comment]
@kksevta Thank you for the feedback. I will check that. Meantime I posted Firefox issue as separate bug. https://github.com/blacklabel/custom_events/issues/57
