### ISSUE TITLE
On LazyLoad redraw() called twice

### ISSUE THREAD

**Issue by Newan** [blacklabel/custom_events#59]
Example:

http://jsfiddle.net/Lh0zrw0k/

On serie.setData(), chart.addSerie() etc the chart redrawed twice

**Comment by sebastianbochan** [comment]
When I run a demo: http://jsfiddle.net/c848uue9/ (without CustomEvents) and http://jsfiddle.net/Lh0zrw0k/ in the both cases I see the same animation (two steps). Could you explain that case in more details?

**Comment by sebastianbochan** [comment]
I rebuild the custom_events.js core and now all should work properly. If problem will appear, please reopen the case.
