### ISSUE TITLE
Unable to select items with allowPointSelect

### ISSUE THREAD

**Issue by sikorsky555** [blacklabel/custom_events#67]
I have my plotOptions set to allowPointSelect for the series. When including the latest version (1.4.2) I can no longer actually select items in HighCharts. This seems to be because we are setting the noop for events. This is with HighCharts version 4.2.6.

**Comment by sebastianbochan** [comment]
Thank you for reporting, I will check that.

**Comment by sebastianbochan** [comment]
I rebuild the custom_events.js core and now all should work properly. If problem will appear, please reopen the case.
