### ISSUE TITLE
Animation of a series

### ISSUE THREAD

**Issue by PaulDalek** [blacklabel/custom_events#68]
#### Behaviour
It seems when custom events plugin is loaded, animation of rendering series on a chart works despite the fact that the series animation is disabled in plotOptions. Also each click on a legend item triggers animation of all series.

#### Live demo with steps to reproduce
http://jsfiddle.net/d_paul/ebraxrv8/1/

**Comment by wbazant** [comment]
We are experiencing this as well in [Expression Atlas](www.ebi.ac.uk/gxa)- we have the animation option disabled for our heatmap, but bringing in custom_events triggers the unwanted animation.

**Comment by sebastianbochan** [comment]
I rebuild the custom_events.js core and now all should work properly. If problem will appear, please reopen the case.
