### ISSUE TITLE
Disable default browser menu

### ISSUE THREAD

**Issue by sebastianbochan** [blacklabel/custom_events#72]
Disable default browser menu, on right click event.

**Comment by wbazant** [comment]
@sebastianbochan I imagine this collided with the right click event in some way. Maybe you'd prefer to only monkeypatch oncontextmenu after a right click handler is registered? If this sounds right but you guys have no time I can have a go at solving this in the library and making a PR, it's about as easy as having a fork or maintaining a patch for your patch.

**Comment by sebastianbochan** [comment]
I will consider it, meatime Im looking for universal solution.
