### ISSUE TITLE
Return values of wrapped methods need to be preserved

### ISSUE THREAD

**Issue by MichaelFroeschen** [blacklabel/custom_events#73]
> Highcharts relies on chaining some of these wrapped methods so we must preserve their return values.
> 
> For example, without this Highcharts loses track of plot lines and plot bands making it impossible to remove them later.

This description is taken from the Pull Request #8 

The described problem still exists in the current version. The reason can be found at line 180.
Because of the fact that the render method is wrapped (and the wrapped method returns false instead of the plotline object) plotlines and plotbands are never actually added.
That leads to several issues like plotbands not being resized.

**Comment by sebastianbochan** [comment]
Thank you for the reporting. I will check that as soon as possible.

**Comment by Drumstix42** [comment]
Yes, I'm seeing the issue with plotLines and had to revert to an older pre-v2 version of the plugin.

If you simply add a plotLine to a basic chart, and zoom in, the plotLine will not update it's location to the new axis value. It stays in it's old position instead.

**Comment by sebastianbochan** [comment]
@Drumstix42 Could you replicate your example as live demo ?

**Comment by MichaelFroeschen** [comment]
I think that this has been fixed with #81

**Comment by sebastianbochan** [comment]
Closed the ticket, if problem will come again, please reopen.
