### ISSUE TITLE
contextmenu no longer works when using custom events

### ISSUE THREAD

**Issue by michaeljho** [blacklabel/custom_events#74]
Hi,

We see that this plugin disables the window contextmenu via a global listener. Is there a particular reason for that? I have need for this plugin but users now complain they can't copy/paste or open in new tab/window via the standard browser context menu.

**Comment by dmackerman** [comment]
Code in question: https://github.com/blacklabel/custom_events/blob/master/js/customEvents.js#L58-L60

**Comment by aaronhuisinga** [comment]
Not sure why this is being ignored, as it's a pretty frustrating side effect for using this package. I'm having to manually override that code before deploying. This should really be fixed.

**Comment by sebastianbochan** [comment]
I will investigate the issue and fix it as soon as possible.

**Comment by sebastianbochan** [comment]
I committed bugfix for it. Let me know if now all works properly with your expectations

**Comment by aaronhuisinga** [comment]
@sebastianbochan This fix is working exactly as expected for me. Thanks!

Can you get this release synced to NPM so that I can use that as my source instead of manually downloading the file? Looks like NPM is still on v2.0.3.

**Comment by sebastianbochan** [comment]
@aaronhuisinga I released the newest 2.0.7 in the NPM. 

Reopen the case when problem will appear again.
