### ISSUE TITLE
Missing data on click on x-axis data labels

### ISSUE THREAD

**Issue by royigoldi** [blacklabel/custom_events#78]
Hi, 

I am using this plugin and groupd categories plugin also:
i defined categories, for example as: 
{name: "test", value: "3", id:"id1"}
{name: "test2", value: "4", id:"id2"}

when i click on x-axis data labels i am getting only the "test" name in this.textStr.
ther ei no this.pos for getting the categories and no addinional data (for example: the value and the id that I defined)

can you help me to understand how i get my addional data (my names are not unique so i need to get the id also by click)

Thanks,
Royi

**Comment by sebastianbochan** [comment]
Thank you for the reporting. Could you replicate your example as live demo on the jsfiddle.net ? It will be helpful in the further debugging.

**Comment by royigoldi** [comment]
Hi,

it is little hard for me because i working on angular 2 project and wrap yours chart...
can you test it by yourself and update me?

Thanks,
Royi

**Comment by royigoldi** [comment]
Hi sebastianbochan,

Did you have any solution for me?

Thanks

**Comment by sebastianbochan** [comment]
At this moment the issue is not reproducible in the native JS. Could you simplify your demo and show me unworking demo as live example?

**Comment by royigoldi** [comment]
Hi,

I update your fiddle:
http://jsfiddle.net/qus1hnyj/1/

please look that if you add same name in the sub category, how i get the relevant item that click beacuse the name is not unique, i change also the click event to dispaly the id property that i add, but it doesn't work...

Thanks,
Royi

**Comment by sebastianbochan** [comment]
The issue is also reproducible without grouped-categrories: 
- http://jsfiddle.net/cc0wnqv6/

The reason of that is context and access to "this". In "this" you have a reference to a SVG element not parameters from xAxis chart's object.
