### ISSUE TITLE
Plugin breaks plot bands with navigators

### ISSUE THREAD

**Issue by mikecentiq** [blacklabel/custom_events#81]
Go to https://jsfiddle.net/hew1jLat/ then use the navigator to zoom in a bit, and then drag it from left to right. You will see that the plot band is erroneously fixed in place on the view of the graph, rather than moving with the data.

If you delete the line:

```html
<script src="https://blacklabel.github.io/custom_events/js/customEvents.js"></script>
```

And then re-run the jsfiddle, you will see it starts to work how it should, with the plot band moving with the graph data.

You'll note, I'm not using any events. The mere act of adding your plugin breaks the combination of plot bands and navigators.

**Comment by mikecentiq** [comment]
Also. After creating the chart, if your plugin is there, then `chart.xAxis[0].plotLinesAndBands` is an empty array. If I remove your module, then it contains the single plot band element which it should.

**Comment by sebastianbochan** [comment]
Thank you for the reporting, I will check it, this week.
