### ISSUE TITLE
Question: get point object on event

### ISSUE THREAD

**Issue by Newan** [blacklabel/custom_events#82]
hello,

is it possible to get the highcharts point object in the event. somethink like:

click: function (evt, point) {

evt.target.point.options.x is not definied if the user cliked on the hover effekt and not in the center of an series point. point is emtpy
Thanks

**Comment by sebastianbochan** [comment]
The point object is available in this.

Run the console and observe object.

Example:
- http://jsfiddle.net/nc5fh8mp/

**Comment by Newan** [comment]
thanks i will check it
