### ISSUE TITLE
problem when the event is mouseovering point in a scatter chart 

### ISSUE THREAD

**Issue by PabloDeo** [blacklabel/custom_events#86]
I have a scatter chart which is supposed to do something when the mouse moves over a point with regards to the x value of the point. When I mouse over a point for the first time, the value of "this.x" is undefined (which should be a number), and value of "this" is a Window object (which should be a point). The program works properly later on (second-time mouse-over, third-time mouse-over).

My code:
...
plotOptions: {
...
                series: {
					point: {
                        events: {
                            mouseover: function () {
                                if(enablemouse){
                                    console.log("id_move_mouse_over_" + this.x);  
                                    console.log(this); //
                                    document.getElementById("id_move_mouse_over_" + this.x).value=1;
                                    //console.log( document.getElementById("id_move_mouse_over_" + this.x).value);
                                }
                            }
                        }
                    }
                }
            },

...

**Comment by sebastianbochan** [comment]
I simplified your demo and it looks that this.x is always extracted.
- http://jsfiddle.net/t69oe8z8/

One of the reasons can be enablemouse flag which you use. Could you update my demo for the further debugging?

**Comment by PabloDeo** [comment]
Sorry I forgot to mention that stickyTracking is set to false:
http://jsfiddle.net/t69oe8z8/2/

**Comment by sebastianbochan** [comment]
Recently I commit the new update for all this references. As I see now all should work properly. Could you confirm?
