### ISSUE TITLE
this returning the wrong data and select event not working

### ISSUE THREAD

**Issue by fender053** [blacklabel/custom_events#87]
Hello,

I have added custom events to my application and now about 30% - 40% of the time "this" is returning the wrong information. 

For example clicking on a point and alerting for the id and name of the point will return the name and id of a different point.

You can try in this fiddle [https://jsfiddle.net/wbwzaLnp/4/](https://jsfiddle.net/wbwzaLnp/4/)

Attempt to left click or right click on the point labeled "+ communications" and it will alert the name and id of the point for "-  Bus vs Mission Conflict". Several other points return a similar behavior, while some act as expected.

The points return the expected data if you remove customEvents.js as an external resource from the fiddle.

I'm not sure if it is related or not, but the point select event also stops working when using customEvents. Again if customEvents is removed, the select event triggers.

**Comment by sebastianbochan** [comment]
Thank you for the reporting. I will investigate the issue and fix it as soon as possible.
