### ISSUE TITLE
this plugin replaces mouseOver with mouseover

### ISSUE THREAD

**Issue by arunkjn** [blacklabel/custom_events#88]
My charts no longer respond to 'mouserOver' and 'mouseOut', but rather to 'mouseover' and 'mouseout'. Also my tooltips are not working anymore. I am using highcharts v4.2.7

**Comment by sebastianbochan** [comment]
Thank you for the reporting. Could you simplify your demo and replicate on the jsfiddle.net ?

**Comment by sebastianbochan** [comment]
Recently I committed the new update, could you confirm that problem still appers? If yes, please replicate it as live demo.

**Comment by sebastianbochan** [comment]
Closed due to inactive.  When problem will come again, please reopen with live demo,
