### ISSUE TITLE
Lost reference to event.point

### ISSUE THREAD

**Issue by vedovelli** [blacklabel/custom_events#89]
Hello team! I hope you're doing fine!

http://api.highcharts.com/highcharts/plotOptions.series.events.click

I'm using series click event and from the event passed to the callback I get the selected point by accessing event.point.

After including custom_events.js to my project, I've lost the ability to access point in the event.

Could you please advise?

Thank you!

Fabio Vedovelli

**Comment by sebastianbochan** [comment]
Thank you for the reporting, I will fix it as soon as possible.

**Comment by vedovelli** [comment]
Looking forward! Thanks a lot!

**Comment by hopest** [comment]
The event does not work if you update the series type, for example:
http://jsfiddle.net/hopest/w85kghvc/1/

**Comment by sebastianbochan** [comment]
Thank you for the feedback. I opened new ticket with this bug here: https://github.com/blacklabel/custom_events/issues/93
