### ISSUE TITLE
On mobile device 'this' in events was not a Highcharts point

### ISSUE THREAD

**Issue by natee** [blacklabel/custom_events#91]
#### Expected behaviour
When dblclick a point, `this` should be the Highcharts point.
![wx20170320-123404](https://cloud.githubusercontent.com/assets/4928035/24088769/9264dc2c-0d69-11e7-802b-050022e19c83.png)

#### Actual behaviour
`this` was svg element
![wx20170320-123458](https://cloud.githubusercontent.com/assets/4928035/24088777/ace6524c-0d69-11e7-9f3e-4f8a8721de97.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/91g0nkro/1/

**Comment by sebastianbochan** [comment]
Thank you for the reporting, I will fix it as soon as possible.
