### ISSUE TITLE
Missing legendItemClick on Pie Chart Point

### ISSUE THREAD

**Issue by arkross** [blacklabel/custom_events#94]
According to [Highcharts documentation](http://api.highcharts.com/highcharts/plotOptions.pie.events.legendItemClick), Pie Chart does not have **legendItemClick** on series level. It can only be added on Point level. So, the legendItemClick is currently unavailable to use on Pie chart with this plugin.

I have fixed the issue apparently, by adding these lines after the original legendItemClick support in the code.

```javascript
// Add support for legendItemClick on Point objects.
if (userOptions && userOptions.point && userOptions.point.events && userOptions.point.events.legendItemClick) {
	options.point.events = {
	      legendItemClick: userOptions.point.events.legendItemClick
	};
}
```

However, this fix has not been tested with another type of chart. Please consider adding this fix. Thank you!

**Comment by sebastianbochan** [comment]
Thank you for the reporting. I will fix it as soon as possible.
