### ISSUE TITLE
Axis labels click event not working properly in 2.0.11+

### ISSUE THREAD

**Issue by aaronhuisinga** [blacklabel/custom_events#95]
Up until v2.0.10, clicking on the label of an axis via a click event would return an object including the axis and series data which made it easy to work with the chart. Starting in v2.0.11 and above, it now returns an SVG object which makes it very difficult to work with the chart.

Not working (using current version of Custom Events): https://jsfiddle.net/3ssLzymy/
Working (using hardcoded v2.0.10): https://jsfiddle.net/4207nh2e/

**Comment by sebastianbochan** [comment]
Thank you for the reporting. I will fix it as soon as possible.

**Comment by aaronhuisinga** [comment]
@sebastianbochan Thanks! Can we get the v2.0.15 release tagged on NPM? It's still showing the latest version as v2.0.14

**Comment by sebastianbochan** [comment]
@aaronhuisinga yes its released (I see 2.0.15). 

Ref:
- https://www.npmjs.com/package/highcharts-custom-events
