### ISSUE TITLE
Events are not applied for bubble chart

### ISSUE THREAD

**Issue by sebastianbochan** [blacklabel/custom_events#97]
Demo:
- http://jsfiddle.net/ptk29xkg/

Context menu is missing for bubble chart.

**Comment by pawelfus** [comment]
FYI: it works fine with 5.0.10: http://jsfiddle.net/ptk29xkg/1/

**Comment by sebastianbochan** [comment]
Since v5.0.12, events work properly.

Demo:
- http://jsfiddle.net/Lvc9ncL9/
